using System;
using Contracts;
using HarmonyLib;
using LmpClient.Systems.ShareContracts;
using LmpCommon.Enums;
using UnityEngine;

// ReSharper disable All

namespace LmpClient.Harmony
{
    /// <summary>
    /// Stock <see cref="Contract.Withdraw"/> is called from multiple stock paths — <c>Contract.Update</c>
    /// when an offered contract's deadline passes, stock surplus cleanup (already guarded at
    /// <see cref="ContractSystem.WithdrawSurplusContracts"/>), and subclass <c>OnOffered</c> validation
    /// (e.g. rescue contracts rejecting unsupported parameters). In stock this is safe because the local
    /// offer pool IS the source of truth; with PersistentSync the server owns the offer pool across the
    /// session. Letting stock silently drop a server-known offered row locally causes the client's offer
    /// list to diverge from the authoritative snapshot until the next server broadcast re-hydrates it —
    /// most visible on reconnect, where a time-jump-triggered <c>Contract.Update</c> sweep withdraws
    /// dozens of offered contracts seconds after the snapshot applies, and the subsequent producer
    /// FullReconcile then published that pruned view back to the server.
    /// <para/>
    /// This guard blocks <see cref="Contract.Withdraw"/> only when (a) PersistentSync is authoritative,
    /// (b) the contract is currently <see cref="Contract.State.Offered"/>, and (c) the contract's GUID
    /// is tracked in the last applied server snapshot. Locally-minted contracts that the server has not
    /// seen (e.g. newly generated during a controlled refresh window that we deliberately let stock run,
    /// or subclass <c>OnOffered</c> rejecting itself before the producer publishes it) still go through
    /// the original method so stock's rejection semantics keep working unchanged. Explicit command
    /// intents (<c>DeclineContract</c> / <c>CancelContract</c>) remain the only supported way to retire
    /// a server-known offer; they transition state on the server which then broadcasts the removal.
    /// </summary>
    [HarmonyPatch(typeof(Contract), nameof(Contract.Withdraw))]
    public class Contract_WithdrawPersistentSyncGuard
    {
        private const float SuppressLogThrottleSeconds = 5f;

        private static Guid _lastSuppressedGuid;

        private static float _lastSuppressedRealtime = -999f;

        [HarmonyPrefix]
        private static bool Prefix(Contract __instance)
        {
            if (__instance == null)
            {
                return true;
            }

            if (MainSystem.NetworkState < ClientState.Connected)
            {
                return true;
            }

            var share = ShareContractsSystem.Singleton;
            if (share == null || !share.Enabled || !share.IsPersistentSyncAuthoritativeForContracts())
            {
                return true;
            }

            // Only guard contracts that are still in the Offered pool. Contracts that already transitioned to
            // Active / Completed / Failed / Withdrawn / Declined are in terminal or player-owned territory, and
            // stock may need to finalize them (e.g. propagate a genuine state transition) — let the original run.
            if (__instance.ContractState != Contract.State.Offered)
            {
                return true;
            }

            // Contracts the server has not yet seen (locally generated by stock between authoritative snapshots)
            // must still be able to withdraw themselves — for example, subclass OnOffered validators on rescue
            // contracts explicitly call Withdraw when they can't resolve a suitable Kerbal/vessel.
            var sender = share.MessageSender;
            if (sender == null || !sender.IsServerKnownContract(__instance.ContractGuid))
            {
                return true;
            }

            var now = Time.realtimeSinceStartup;
            if (__instance.ContractGuid != _lastSuppressedGuid || now - _lastSuppressedRealtime >= SuppressLogThrottleSeconds)
            {
                _lastSuppressedGuid = __instance.ContractGuid;
                _lastSuppressedRealtime = now;
                LunaLog.Log(
                    $"[PersistentSync] Contract.Withdraw suppressed (PersistentSync authoritative) " +
                    $"guid={__instance.ContractGuid} title={__instance.Title}");
            }

            return false;
        }
    }
}
